DATA SEGMENT
M1 DB 10,13,"ENTER THE STRING:$"
M2 DB 10,13,"LENGHT OF STRING IS:$ "
M3 DB 10,13,"REVERSE STRING IS:$"
M4 DB 10,13,"STRING IS PALINDROMI OR NOT??$"
M5 DB 10,13,"STRING IS PALINDROMI$"
M6 DB 10,13,"STRING IS NOT PALINDROMI$"
Str1 DB 20 DUP('#')
Str2 DB 20 DUP ('#')
COUNT DB 0000H        ; To store number of characters
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE,DS:DATA,ES:DATA
START:
MOV AX,DATA
MOV DS,AX
MOV ES,AX

LEA SI,Str1
LEA DI,Str2

;--------------- Read the String--------------------------
MOV AH,09H
LEA DX,M1
INT 21H
MOV CL,00H
L1:MOV AH,01H
INT 21H
mov [si],al
inc si
INC COUNT
CMP AL,'#'
JNE L1
DEC COUNT

 ;-------------------------------------------------
MOV AH,09H
LEA DX,M2
INT 21H
CALL LEN_DSP

MOV AH,09H
LEA DX,M3
INT 21H
CALL REVERSE


MOV AH,09H
LEA DX,M4
INT 21H

CALL PALINDROME

MOV AH,4CH
INT 21H
 ;---------------------- Reverse String Operation-------------
REVERSE PROC
LEA SI,STR1
LEA DI,STR2
MOV CL,[COUNT]
MOV CH,00
ADD SI,CX
DEC SI
P1:MOV AL,[SI]
MOV [DI],AL
INC DI
MOV DL,AL
MOV AH,02H
INT 21H
DEC SI
LOOP P1
 RET
REVERSE ENDP
 ;------------------ Display Lenght of String Operation-----------------
LEN_DSP PROC
MOV AL,COUNT
MOV CL,04H
SHr  AL,CL
CMP AL,39H
JLE L2
add AL,07H
L2:add AL,30H
MOV DL,AL
MOV AH,02H
INT 21H

MOV AL,COUNT
AND AL,0FH
CMP AL,39H
JLE L3
ADD AL,07H
L3:ADD AL,30H
MOV DL,AL
MOV AH,02H
INT 21H
RET
LEN_DSP ENDP
 ;------------- Check  String is Palindrome or not Operation----------
PALINDROME PROC
LEA SI,STR1
LEA DI,STR2
MOV CL,[COUNT]
Z1:MOV AL,[SI]
MOV BL,[DI]
INC SI
INC DI
CMP AL,BL
JNE Z2

MOV AH,09H
LEA DX,M5
INT 21H
RET
Z2:MOV AH,09H
LEA DX,M6
INT 21H
RET
PALINDROME ENDP


CODE ENDS
END START